class RegimeRules:
    # Thresholds
    ADX_TRENDING_THRESHOLD = 25
    ATR_VOLATILITY_THRESHOLD_PERCENTILE = 70 # e.g., if ATR > 70th percentile of last N ATRs
    RS_VOLATILITY_THRESHOLD = 0.05

    # Regime Labels
    STRONG_TREND = "STRONG_TREND"
    WEAK_TREND = "WEAK_TREND"
    RANGING = "RANGING"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LOW_VOLATILITY = "LOW_VOLATILITY"
