import pandas as pd
from .trend_features import TrendFeatures
from .momentum_features import MomentumFeatures
from .volatility_features import VolatilityFeatures
from .volume_features import VolumeFeatures

class FeatureStore:
    def __init__(self):
        pass

    def generate_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Orchestrates the generation of all features.
        """
        if df is None:
            return None
        
        # Create a copy to preserve original
        features = df.copy()
        
        # Ensure numerical types
        cols = ['open', 'high', 'low', 'close', 'tick_volume']
        for col in cols:
            features[col] = pd.to_numeric(features[col], errors='coerce')
        
        features.dropna(subset=cols, inplace=True)

        # Add Trend Features
        features = TrendFeatures.add_all_trend_features(features)

        # Add Momentum Features
        features = MomentumFeatures.add_all_momentum_features(features)

        # Add Volatility Features
        features = VolatilityFeatures.add_all_volatility_features(features)

        # Add Volume Features
        features = VolumeFeatures.add_all_volume_features(features)

        # Drop NaN values generated by indicators (e.g. initial lookback period)
        features.dropna(inplace=True)
        features.reset_index(drop=True, inplace=True)

        return features
